package collector

const (
	versionField                       = "VERSION"
	uptimeField                        = "UPTIME"
	bpsInField                         = "BPS_IN"
	bpsOutField                        = "BPS_OUT"
	sslBpsInField                      = "SSL_BPS_IN"
	sslBpsOutField                     = "SSL_BPS_OUT"
	maxconnField                       = "MAXCONN"
	maxsslConnField                    = "MAXSSL_CONN"
	plainconnField                     = "PLAINCONN"
	availconnField                     = "AVAILCONN"
	idleconnField                      = "IDLECONN"
	sslconnField                       = "SSLCONN"
	availsslField                      = "AVAILSSL"
	reqRateField                       = "REQ_RATE"
	reqRateReqProcessingField          = "REQ_RATE_REQ_PROCESSING"
	reqRateReqPerSecField              = "REQ_RATE_REQ_PER_SEC"
	reqRateTotReqsField                = "REQ_RATE_TOT_REQS"
	reqRatePubCacheHitsPerSecField     = "REQ_RATE_PUB_CACHE_HITS_PER_SEC"
	reqRateTotalPubCacheHitsField      = "REQ_RATE_TOTAL_PUB_CACHE_HITS"
	reqRatePrivateCacheHitsPerSecField = "REQ_RATE_PRIVATE_CACHE_HITS_PER_SEC"
	reqRateTotalPrivateCacheHitsField  = "REQ_RATE_TOTAL_PRIVATE_CACHE_HITS"
	reqRateStaticHitsPerSecField       = "REQ_RATE_STATIC_HITS_PER_SEC"
	reqRateTotalStaticHitsField        = "REQ_RATE_TOTAL_STATIC_HITS"
	extappField                        = "EXTAPP"
	extappCmaxconnField                = "EXTAPP_CMAXCONN"
	extappEmaxconnField                = "EXTAPP_EMAXCONN"
	extappPoolSizeField                = "EXTAPP_POOL_SIZE"
	extappInuseConnField               = "EXTAPP_INUSE_CONN"
	extappIdleConnField                = "EXTAPP_IDLE_CONN"
	extappWaitqueDepthField            = "EXTAPP_WAITQUE_DEPTH"
	extappReqPerSecField               = "EXTAPP_REQ_PER_SEC"
	extappTotReqsField                 = "EXTAPP_TOT_REQS"
)
